apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: javawebapp
  name: javawebapprc  
spec:
  replicas: 2
  selector:
    run: javawebapp
  template:
    metadata:
      labels:
        run: javawebapp
      name: javawebapprc        
    spec:
      containers:
      - image: ankita006/java-app:4
        name: javawebapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    run: javawebapp
  ports:
  - port: 80
    targetPort: 8080
