apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: javawebappdep
  name: javawebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        run: javawebapp
      name: javawebapprc        
    spec:
      containers:
      - image: ankita006/java-app:4
        name: javawebapp
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    run: javawebapp
  ports:
  - port: 80
    targetPort: 8080
