apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:    
      name: springbootpod
      labels:
        app: springboot
    spec:
      containers:
      - image: ankita006/spring-boot-mongo:4
        name: springbootcont
        ports:
        - containerPort: 8080
        env:  
        - name: MONGO_DB_HOSTNAME
          value: mongo
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123

---
apiVersion: v1
kind: Service
metadata:
  name: springbootsvc
spec:
  type: NodePort
  selector:
    app: springboot
  ports: 
  - port: 80
    targetPort: 8080
    #    NodePort: 32124

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongodbrc
spec:
  selector:
    app: mongodb
  template:
    metadata:
      name: mongodbpod
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodbcont
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017  

    

      
  




    

